### ISSUE TITLE
Schduler has problems with the topo_nav travel_time_estimator

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_executive#108]
this happened when trying to schedule and on demand task while running the simple node patrol.

```
[INFO] [WallTime: 1416340619.241509] Requesting preempt on state machine in state ['TASK_NAVIGATION']
[INFO] [WallTime: 1416340619.241817] Waiting for exit
[INFO] [WallTime: 1416340619.241916] Preempt requested on action 'topological_navigation'
[INFO] [WallTime: 1416340619.242330] Preempt on action 'topological_navigation' cancelling goal: 
target: WayPoint21
[INFO] [WallTime: 1416340619.460458] Concurrent state 'MONITORING' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416340619.617749] Concurrent state 'MONITORED' returned outcome 'preempted' on termination.
[WARN] [WallTime: 1416340619.618491] State 'MONITORING' in concurrence did not service preempt.
[INFO] [WallTime: 1416340619.618889] Concurrent Outcomes: {'MONITORED': 'preempted', 'MONITORING': 'preempted'}
[INFO] [WallTime: 1416340619.619064] Nav terminated with outcome preempted
[INFO] [WallTime: 1416340619.621603] State machine transitioning 'TASK_NAVIGATION':'preempted'-->'TASK_CANCELLED'
[INFO] [WallTime: 1416340619.622227] Preempt requested on state machine before executing the next state.
[INFO] [WallTime: 1416340619.622465] Last state 'TASK_NAVIGATION' did not service preempt. Preempting next state 'TASK_CANCELLED' before executing...
[INFO] [WallTime: 1416340619.622731] Execution of task 20 was cancelled
[INFO] [WallTime: 1416340619.625192] start window: 1416337800.0
[INFO] [WallTime: 1416340619.625437]          now: 1416340619.625149965
[INFO] [WallTime: 1416340619.625671] start window is open
[INFO] [WallTime: 1416340619.625926] State machine terminating 'TASK_CANCELLED':'preempted':'preempted'
[INFO] [WallTime: 1416340619.629272] Next task to execute: 19
[INFO] [WallTime: 1416340619.657006] And relax
[INFO] [WallTime: 1416340619.657216] Execution of task 19 was requested
[INFO] [WallTime: 1416340619.657476] Task 24, execute_maraton_task demanded from scheduler
[WARN] [WallTime: 1416340619.660207] lower bound 1416340676171660925
[WARN] [WallTime: 1416340619.661034] Dropped 1 existing tasks which are no longer executable
[INFO] [WallTime: 1416340619.661530] Including current task 19 in scheduling problem
[ERROR] [WallTime: 1416340619.662415] Error raised during SMACH container construction: 
Traceback (most recent call last):

  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/sm_base_executor.py", line 251, in execute_task
    monitor_duration = self.expected_navigation_duration(task) * 3

  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 118, in expected_navigation_duration
    et = self.expected_time(start=self.current_node, target=task.start_node_id)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)

ServiceException: service [/topological_navigation/travel_time_estimator] returned no response

[ERROR] [WallTime: 1416340619.662766] Error raised during SMACH container construction: 
Traceback (most recent call last):

  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/sm_base_executor.py", line 251, in execute_task
    monitor_duration = self.expected_navigation_duration(task) * 3

  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 118, in expected_navigation_duration
    et = self.expected_time(start=self.current_node, target=task.start_node_id)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 517, in call
    raise ServiceException("service [%s] returned no response"%self.resolved_name)

ServiceException: service [/topological_navigation/travel_time_estimator] returned no response
```

**Comment by cdondrup** [comment]
Different error but same cause: trying to schedule an on demand task when there are already many in the queue:

```
[INFO] [WallTime: 1416355580.657643] Task 28, execute_marathon_task demanded from scheduler
[WARN] [WallTime: 1416355580.660375] lower bound 1416355660052460457
[WARN] [WallTime: 1416355580.661070] Dropped 1 existing tasks which are no longer executable
[INFO] [WallTime: 1416355580.661339] Including current task 25 in scheduling problem
[INFO] [WallTime: 1416355580.685469] Next task to execute: 25
[INFO] [WallTime: 1416355580.685850] Execution of task 25 was requested
[INFO] [WallTime: 1416355580.695175] State machine starting in initial state 'TASK_INITIALISATION' with userdata: 
    ['task']
[ERROR] [WallTime: 1416355580.705902] InvalidUserCodeError: Could not execute state 'TASK_INITIALISATION' of type '<task_executor.sm_base_executor.TaskInitialisation object at 0x7f254c0953d0>': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/sm_base_executor.py", line 97, in execute
    self.executor.prepare_task(userdata.task)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 264, in prepare_task
    expected_nav_duration = self.expected_navigation_duration(task)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 116, in expected_navigation_duration
    et = self.expected_time(start=self.closest_node, target=task.start_node_id)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

Exception in thread Thread-112:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 347, in execute
    container_outcome = self._update_once()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 246, in _update_once
    raise smach.InvalidUserCodeError("Could not execute state '%s' of type '%s': " % ( self._current_label, self._current_state ) + traceback.format_exc())
InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x7f25480134d0>

[ INFO] [1416355581.325875614]: Got a request for a schedule 20 tasks 
[ INFO] [1416355581.325919600]: 25 is first
[ INFO] [1416355581.353331631]: Going to solve
[INFO] [WallTime: 1416355581.365875] task_order: [25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6]
```

**Comment by hawesie** [comment]
I don't see this when I test things. Are you sure you're demanding to a waypoint that exists? What happens if you run `rosrun task_executor example_demand_client.py` which demands a single wait action? What if you run the dummy top nav rather than the real one? E.g. replace the whole strands navigation with `roslaunch topological_utils dummy_topological_navigation.launch map:=<map>` and try again.

I will keep exploring though.

**Comment by cdondrup** [comment]
All I can say is that it works if the schedule is empty. Will try your suggestions and report back.

**Comment by cdondrup** [comment]
OK, I tested it again, when I get the error described in https://github.com/strands-project/strands_executive/issues/108#issuecomment-63570234 I also observed this output in the action server that should execute the task:

```
[WARN] [WallTime: 1416404068.529863] Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
```

Which would mean that the action server became unresponsive?! This is the action server: https://github.com/LCAS/marathon_gui/blob/master/scripts/execute_task.py very simple. All this happened before the robot started moving, so I guess it's the scheduler trying to create a client or something?

The error https://github.com/strands-project/strands_executive/issues/108#issue-49286578 seems to be related with the robot being stuck and then requesting a task. I observed this from the navigation:

```
[DEBUG] [WallTime: 1416405564.364406] ERROR: Broken Pipe
[DEBUG] [WallTime: 1416405564.365313] publisher connection to [/patroller_routine] terminated, see errorlog for details:
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 621, in write_data
    self.socket.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 991, in publish
    c.write_data(data)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 630, in write_data
    raise TransportTerminated(str(errno)+msg)
rospy.exceptions.TransportTerminated: 32Broken pipe
```

A different error when the robot is stuck is:

```
[ERROR] [WallTime: 1416405726.380621] InvalidUserCodeError: Could not execute state 'TASK_INITIALISATION' of type '<task_executor.sm_base_executor.TaskInitialisation object at 0x24c21d0>': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/sm_base_executor.py", line 97, in execute
    self.executor.prepare_task(userdata.task)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 264, in prepare_task
    expected_nav_duration = self.expected_navigation_duration(task)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 116, in expected_navigation_duration
    et = self.expected_time(start=self.closest_node, target=task.start_node_id)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

Exception in thread Thread-31:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 347, in execute
    container_outcome = self._update_once()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 246, in _update_once
    raise smach.InvalidUserCodeError("Could not execute state '%s' of type '%s': " % ( self._current_label, self._current_state ) + traceback.format_exc())
InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x7f6cb401b9e0>
```

**Comment by cdondrup** [comment]
This happened when just repeatedly trying to schedule a task:

```
[ERROR] [WallTime: 1416406355.514556] InvalidUserCodeError: Could not execute state 'TASK_INITIALISATION' of type '<task_executor.sm_base_executor.TaskInitialisation object at 0x3729990>': Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 241, in _update_once
    self._remappings[self._current_label]))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/sm_base_executor.py", line 97, in execute
    self.executor.prepare_task(userdata.task)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 264, in prepare_task
    expected_nav_duration = self.expected_navigation_duration(task)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 116, in expected_navigation_duration
    et = self.expected_time(start=self.closest_node, target=task.start_node_id)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 512, in call
    transport.send_message(request, self.seq)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 607, in send_message
    self.write_buff.truncate(0)
AttributeError: 'NoneType' object has no attribute 'truncate'

Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 347, in execute
    container_outcome = self._update_once()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/smach/state_machine.py", line 246, in _update_once
    raise smach.InvalidUserCodeError("Could not execute state '%s' of type '%s': " % ( self._current_label, self._current_state ) + traceback.format_exc())
InvalidUserCodeError: <smach.exceptions.InvalidUserCodeError instance at 0x7f4bac01e1b8>
```

Robot was not stuck.

**Comment by cdondrup** [comment]
Just tried it again, restarted the scheduler and the continuous patrol, above error occures after trying to schedule the same task for 5-6 times. It is exactly the same task again and again as I'm just pressing the button on the website. Most of the times it "works" (where works means that it ignores it but it doesn't break) but sometimes it just crashes. The robot stops moving and the scheduler does not execute tasks any more but is still responsive and doesn't die.

**Comment by cdondrup** [comment]
This is the output of the `example_demand_client.py` when she was stuck:

```
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/task_executor/example_demand_client.py", line 33, in <module>
    task_id = demand_task(demanded_wait)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 515, in call
    responses = transport.receive_once()
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 667, in receive_once
    p.read_messages(b, msg_queue, sock) 
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 353, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 336, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
rospy.service.ServiceException: service [/task_executor/demand_task] responded with an error: service cannot process request: service [/topological_navigation/travel_time_estimator] returned no response
```

Therefore, the `travel_times` issue seems to be related to being stuck.

**Comment by hawesie** [comment]
But `travel_times` is very simple so I can't think of why it would cause problems, except if perhaps there are lots of concurrent service calls, so maybe this is concurrency issue. I will try to explore this in the next few hours. Please can you send me an export of your top map so I can work with that too? And when you say "stuck" what do you mean?

**Comment by cdondrup** [comment]
The topo map is here: https://github.com/strands-project/strands_systems/blob/deprecated/strands_uol_sim/resources/mht.tpl and it's inside the uol_mht strands_morse environment.
With "stuck" I mean that the navigation failed to recover due to being too close to an obstacle.

**Comment by hawesie** [comment]
There's definitely a concurrency issue at my end.

**Comment by hawesie** [comment]
Please could you checkout https://github.com/strands-project/strands_navigation/pull/141 and see if that fixes your problem? I added locking to the travel time estimator and that seems to have cleaned this up.

The problem was (I think) that the task executor calls the estimator during the first step of execution which is free to happen once a task has been demanded. If a task is demanded in quick succession then the setup calls to the the estimator made by the scheduler clash with the one in progress in the executor. The executor is cancelled during this process, but it can't always cancel before this happens.

**Comment by mudrole1** [comment]
I checked my part of the code and support for on demand task is there (@hawesie I was incorrect when we talk about). The important thing from my side, it support only ONE on demand task in one batch of task. The idea is that on demand task needs to happen now, so the order of task needs to be pushed... if you have more of them, my scheduler just take first into account to set the order. So, it should do at least something for on demand tasks. I try it just my laptop and it worked.

**Comment by hawesie** [comment]
Ok. This also matches what I saw in my tests too. @cdondrup what’s your latest on this?=

**Comment by cdondrup** [comment]
Been working on the interface to fix some twitter stuff. Will test your PR asap and also try and run patrolling on the robot and scheduling a task. Won't be able to do that for the next 2 hours or so, but will come back to you asap.

Thanks for all the help so far.

**Comment by cdondrup** [comment]
@hawesie couldn't reproduce the error with the travel times so it might be gone. Will report here if it reoccurs. However, I found a new one:

```
[ERROR] [WallTime: 1416505874.110363] Error raised during SMACH container construction: 
Traceback (most recent call last):

  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/sm_base_executor.py", line 251, in execute_task
    monitor_duration = self.expected_navigation_duration(task) * 3

  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 118, in expected_navigation_duration
    et = self.expected_time(start=self.current_node, target=task.start_node_id)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))

ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

[ERROR] [WallTime: 1416505874.110674] Error raised during SMACH container construction: 
Traceback (most recent call last):

  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/sm_base_executor.py", line 251, in execute_task
    monitor_duration = self.expected_navigation_duration(task) * 3

  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 118, in expected_navigation_duration
    et = self.expected_time(start=self.current_node, target=task.start_node_id)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))

ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/hydro/lib/task_executor/scheduled_task_executor.py", line 331, in execute_tasks
    self.execute_task(next_task)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/sm_base_executor.py", line 251, in execute_task
    monitor_duration = self.expected_navigation_duration(task) * 3
  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 118, in expected_navigation_duration
    et = self.expected_time(start=self.current_node, target=task.start_node_id)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
```

The sender reported a TCP timeout

**Comment by cdondrup** [comment]
Also this one:

```
[INFO] [WallTime: 1416506414.861914] Requesting preempt on state machine in state ['TASK_NAVIGATION']
[INFO] [WallTime: 1416506414.862216] Waiting for exit
[INFO] [WallTime: 1416506414.862294] Preempt requested on action 'topological_navigation'
[INFO] [WallTime: 1416506414.862568] Preempt on action 'topological_navigation' cancelling goal: 
target: WayPoint10
[INFO] [WallTime: 1416506415.238356] Concurrent state 'MONITORED' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1416506415.282925] Concurrent state 'MONITORING' returned outcome 'preempted' on termination.
[WARN] [WallTime: 1416506415.284010] State 'MONITORING' in concurrence did not service preempt.
[INFO] [WallTime: 1416506415.284390] Concurrent Outcomes: {'MONITORED': 'preempted', 'MONITORING': 'preempted'}
[INFO] [WallTime: 1416506415.284718] Nav terminated with outcome preempted
[INFO] [WallTime: 1416506415.288869] State machine transitioning 'TASK_NAVIGATION':'preempted'-->'TASK_CANCELLED'
[INFO] [WallTime: 1416506415.289703] Preempt requested on state machine before executing the next state.
[INFO] [WallTime: 1416506415.290073] Last state 'TASK_NAVIGATION' did not service preempt. Preempting next state 'TASK_CANCELLED' before executing...
[INFO] [WallTime: 1416506415.290509] Execution of task 9 was cancelled
[INFO] [WallTime: 1416506415.293891] start window: 1416505800.0
[INFO] [WallTime: 1416506415.294379]          now: 1416506415.293817996
[INFO] [WallTime: 1416506415.294723] start window is open
[INFO] [WallTime: 1416506415.295113] State machine terminating 'TASK_CANCELLED':'preempted':'preempted'
[INFO] [WallTime: 1416506415.296946] Next task to execute: 8
[INFO] [WallTime: 1416506415.327206] And relax
[INFO] [WallTime: 1416506415.327301] Execution of task 8 was requested
[INFO] [WallTime: 1416506415.328433] Task 31, execute_marathon_task demanded from scheduler
[WARN] [WallTime: 1416506415.330273] lower bound 1416506466693167781
[WARN] [WallTime: 1416506415.331022] Dropped 1 existing tasks which are no longer executable
[INFO] [WallTime: 1416506415.331443] Including current task 8 in scheduling problem
[INFO] [WallTime: 1416506415.334815] State machine starting in initial state 'TASK_INITIALISATION' with userdata: 
    ['task']
[ERROR] [WallTime: 1416506415.335950] Error processing request: 'NoneType' object has no attribute 'close'
['Traceback (most recent call last):\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/task_executor/base_executor.py", line 190, in demand_task_ros_srv\n    self.task_demanded(req.task, self.active_task)\n', '  File "/opt/ros/hydro/lib/task_executor/scheduled_task_executor.py", line 112, in task_demanded\n    success, added = self.try_schedule(previously_scheduled)\n', '  File "/opt/ros/hydro/lib/task_executor/scheduled_task_executor.py", line 277, in try_schedule\n    if self.call_scheduler(to_schedule, lower_bound, current_id):\n', '  File "/opt/ros/hydro/lib/task_executor/scheduled_task_executor.py", line 164, in call_scheduler\n    resp = self.schedule_srv(tasks, earliest_start, current_id, self.get_duration_matrix(tasks))\n', '  File "/opt/ros/hydro/lib/task_executor/scheduled_task_executor.py", line 143, in get_duration_matrix\n    durations[start][end] = self.get_duration(start, end)\n', '  File "/opt/ros/hydro/lib/task_executor/scheduled_task_executor.py", line 127, in get_duration\n    return self.expected_time(start=start, target=end).travel_time\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__\n    return self.call(*args, **kwds)\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 528, in call\n    transport.close()\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 778, in close\n    self.socket.close()\n', "AttributeError: 'NoneType' object has no attribute 'close'\n"]
[INFO] [WallTime: 1416506415.341450] expected_nav_duration:  10.0
[INFO] [WallTime: 1416506415.341719] State machine transitioning 'TASK_INITIALISATION':'succeeded'-->'TASK_NAVIGATION'
```

**Comment by hawesie** [comment]
These are really odd. Why do we see these issues for this new, apparently simple, service, but no-where else. I will add exception handling around these calls so they don't bring the system down.

**Comment by hawesie** [comment]
Looking at the code, the real question is how this ever worked...

**Comment by hawesie** [comment]
A very important part was commented out!
