### ISSUE TITLE
field success is not a bool

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_executive#163]
```
[ERROR] [WallTime: 1428514962.118516] bad callback: <bound method RobotRoutine._check_idle of <routine_behaviours.robot_routine.RobotRoutine object at 0x7fcb5545c510>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 702, in _invoke_callback
    cb(msg)
  File "/home/strands/1f_ws/src/strands_executive_behaviours/routine_behaviours/src/routine_behaviours/robot_routine.py", line 195, in _check_idle
    self.on_idle()
  File "/home/strands/1f_ws/src/strands_executive_behaviours/routine_behaviours/src/routine_behaviours/robot_routine.py", line 339, in on_idle
    self.demand_charge(self.idle_charge_duration)
  File "/home/strands/1f_ws/src/strands_executive_behaviours/routine_behaviours/src/routine_behaviours/robot_routine.py", line 295, in demand_charge
    self.demand_task(charge_task)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 515, in call
    responses = transport.receive_once()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 696, in receive_once
    p.read_messages(b, msg_queue, sock)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 353, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 336, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
ServiceException: service [/task_executor/demand_task] responded with an error: error processing request: field success is not a bool
```

**Comment by bfalacerda** [comment]
this started happening  in bob sometime during the afternoon and now it's happening many times in a row

**Comment by hawesie** [comment]
Are there errors on the executive window too?

**Comment by bfalacerda** [comment]
yes, pretty much the same:

```
[ERROR] [WallTime: 1428519640.057610] Error processing request: field success is not a bool
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 627, in _handle_request\n    transport.send_message(response, self.seq)\n', '  File "/opt/
ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 634, in send_message\n    serialize_message(self.write_buff, seq, msg)\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msg.py", line 
152, in serialize_message\n    msg.serialize(b)\n', '  File "/home/strands/1f_ws/devel/lib/python2.7/dist-packages/strands_executive_msgs/srv/_DemandTask.py", line 433, in serialize\n    except struct.error as se: self._
check_types(struct.error("%s: \'%s\' when writing \'%s\'" % (type(se), str(se), str(_x))))\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/genpy/message.py", line 331, in _check_types\n    check_type(n, t, getat
tr(self, n))\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/genpy/message.py", line 215, in check_type\n    raise SerializationError(\'field %s is not a bool\'%(field_name))\n', 'SerializationError: field succe
ss is not a bool\n']
```

There were another error that appeared meanwhile, not sure if they're related:

```
ERROR] [WallTime: 1428519655.657482] InvalidUserCodeError: Could not execute state 'TASK_FAILED' of type '<task_executor.sm_base_executor.TaskFailed object at 0x7fdca4f31190>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/strands/1f_ws/src/strands_executive/task_executor/src/task_executor/sm_base_executor.py", line 64, in execute
    self.executor.task_failed(completed)
  File "/home/strands/1f_ws/src/strands_executive/task_executor/src/task_executor/base_executor.py", line 44, in task_failed
    self.task_complete(task)
  File "/home/strands/1f_ws/src/strands_executive/task_executor/scripts/scheduled_task_executor.py", line 117, in task_complete
    self.execution_schedule.task_complete(task)
  File "/home/strands/1f_ws/src/strands_executive/task_executor/src/task_executor/execution_schedule.py", line 108, in task_complete
    assert task.task_id == self.current_task.task_id
AssertionError

Exception in thread Thread-750:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
InvalidUserCodeError: Could not execute state 'TASK_FAILED' of type '<task_executor.sm_base_executor.TaskFailed object at 0x7fdca4f31190>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/strands/1f_ws/src/strands_executive/task_executor/src/task_executor/sm_base_executor.py", line 64, in execute
    self.executor.task_failed(completed)
  File "/home/strands/1f_ws/src/strands_executive/task_executor/src/task_executor/base_executor.py", line 44, in task_failed
    self.task_complete(task)
  File "/home/strands/1f_ws/src/strands_executive/task_executor/scripts/scheduled_task_executor.py", line 117, in task_complete
    self.execution_schedule.task_complete(task)
  File "/home/strands/1f_ws/src/strands_executive/task_executor/src/task_executor/execution_schedule.py", line 108, in task_complete
    assert task.task_id == self.current_task.task_id
AssertionError
```

**Comment by bfalacerda** [comment]
more complete output. Executive:

```
[INFO] [WallTime: 1428567001.522376] Nav started to ChargingPoint for task 378, action wait_action
[INFO] [WallTime: 1428567001.592944] The specification is: R{"time"}min=? [ (F "ChargingPoint") ]
ENTERED SET MDP
CALING PREDICT SERVICE
CALLED PREDICT SERVICE
LEAVING SET MDP
received: plan
planned
[INFO] [WallTime: 1428567001.733965] Expected time from current node: 0.0

[INFO] [WallTime: 1428567001.734781] The product has a total of 39 states.
[INFO] [WallTime: 1428567001.735480] Automaton states distances to goal: [1.0, 0]
[INFO] [WallTime: 1428567001.742520] Policy: ['WayPoint5_Station', 'WayPoint12_WayPoint11', 'WayPoint13_WayPoint10', 'WayPoint2_WayPoint5', 'WayPoint4_WayPoint2', 'WayPoint6_WayPoint4', 'WayPoint7_WayPoint6', 'WayPoint9_
WayPoint3', 'WayPoint11_WayPoint1', 'WayPoint1_WayPoint9', 'WayPoint8_WayPoint7', 'WayPoint10_WayPoint8', 'WayPoint3_WayPoint17', 'Station_ChargingPoint', 'WayPoint14_WayPoint16', 'WayPoint15_WayPoint16', 'WayPoint16_Sta
tion', 'WayPoint17_WayPoint18', 'WayPoint18_WayPoint16', None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[INFO] [WallTime: 1428567002.108521] Topological navigation execute policy action server exited with status: SUCCEEDED
[INFO] [WallTime: 1428567002.109095] Policy execution successful.
[INFO] [WallTime: 1428567002.131120] Concurrent state 'MONITORED' returned outcome 'succeeded' on termination.
[INFO] [WallTime: 1428567002.534946] Concurrent state 'MONITORING' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1428567002.536958] Concurrent Outcomes: {'MONITORED': 'succeeded', 'MONITORING': 'preempted'}
[INFO] [WallTime: 1428567002.537648] Nav terminated with outcome succeeded
[INFO] [WallTime: 1428567002.551236] State machine transitioning 'TASK_NAVIGATION':'succeeded'-->'TASK_EXECUTION'
[INFO] [WallTime: 1428567002.553659] Concurrence starting with userdata: 
        ['task']
[INFO] [WallTime: 1428567002.554235] Action wait_action started for task 378
[INFO] [WallTime: 1428567002.619176] target wait time: 2015-04-09 09:11:02
^B^B^B[INFO] [WallTime: 1428567062.624845] waited until: 2015-04-09 09:11:02
[INFO] [WallTime: 1428567062.663198] Concurrent state 'MONITORED' returned outcome 'succeeded' on termination.
^B[INFO] [WallTime: 1428567063.632572] Concurrent state 'MONITORING' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1428567063.666808] Concurrent Outcomes: {'MONITORED': 'succeeded', 'MONITORING': 'preempted'}
[INFO] [WallTime: 1428567063.667328] Action terminated with outcome succeeded
[INFO] [WallTime: 1428567063.675242] State machine transitioning 'TASK_EXECUTION':'succeeded'-->'TASK_SUCCEEDED'
[INFO] [WallTime: 1428567063.684646] Execution of task 378 succeeded
[INFO] [WallTime: 1428567063.685031] State machine terminating 'TASK_SUCCEEDED':'succeeded':'succeeded'
^B^[[B^[[B[INFO] [WallTime: 1428567086.403295] Task 379, wait_action demanded from scheduler
[INFO] [WallTime: 1428567086.403576] start window: 0.0
[INFO] [WallTime: 1428567086.403728]          now: 1428567086.403542995
[INFO] [WallTime: 1428567086.404065] start window is open
[ERROR] [WallTime: 1428567086.409911] Error processing request: field success is not a bool
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 627, in _handle_request\n    transport.send_message(response, self.seq)\n', '  File "/opt/
ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 634, in send_message\n    serialize_message(self.write_buff, seq, msg)\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/msg.py", line 
152, in serialize_message\n    msg.serialize(b)\n', '  File "/home/strands/1f_ws/devel/lib/python2.7/dist-packages/strands_executive_msgs/srv/_DemandTask.py", line 433, in serialize\n    except struct.error as se: self._
check_types(struct.error("%s: \'%s\' when writing \'%s\'" % (type(se), str(se), str(_x))))\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/genpy/message.py", line 331, in _check_types\n    check_type(n, t, getat
tr(self, n))\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/genpy/message.py", line 215, in check_type\n    raise SerializationError(\'field %s is not a bool\'%(field_name))\n', 'SerializationError: field succe
ss is not a bool\n']
[INFO] [WallTime: 1428567086.422554] Next task to execute: 379
[INFO] [WallTime: 1428567086.423740] Execution of task 379 was requested
ENTERD SERVICE
ENTERED SET MDP
```

Routine:

```
[INFO] [WallTime: 1428567171.418441] Idle for too long, going to charging point
CHARGE TASK task_id: 0
start_node_id: ChargingPoint
end_node_id: ChargingPoint
action: wait_action
start_after: 
  secs: 0
  nsecs: 0
end_before: 
  secs: 0
  nsecs: 0
max_duration: 
  secs: 60
  nsecs: 0
execution_time: 
  secs: 0
  nsecs: 0
arguments: 
  - 
    first: "____time____"
    second: 0.0
  - 
    first: "____duration____"
    second: 60.0
[ERROR] [WallTime: 1428567171.438839] bad callback: <bound method RobotRoutine._check_idle of <routine_behaviours.robot_routine.RobotRoutine object at 0x7fcb5545c510>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 702, in _invoke_callback
    cb(msg)
  File "/home/strands/1f_ws/src/strands_executive_behaviours/routine_behaviours/src/routine_behaviours/robot_routine.py", line 195, in _check_idle
    self.on_idle()
  File "/home/strands/1f_ws/src/strands_executive_behaviours/routine_behaviours/src/routine_behaviours/robot_routine.py", line 339, in on_idle
    self.demand_charge(self.idle_charge_duration)
  File "/home/strands/1f_ws/src/strands_executive_behaviours/routine_behaviours/src/routine_behaviours/robot_routine.py", line 295, in demand_charge
    self.demand_task(charge_task)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 515, in call
    responses = transport.receive_once()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 696, in receive_once
    p.read_messages(b, msg_queue, sock)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 353, in read_messages
    self._read_ok_byte(b, sock)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 336, in _read_ok_byte
    raise ServiceException("service [%s] responded with an error: %s"%(self.resolved_name, str))
ServiceException: service [/task_executor/demand_task] responded with an error: error processing request: field success is not a bool
```
