### ISSUE TITLE
lock issue when adding co safe tasks

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/strands_executive#284]
```
ERROR] [WallTime: 1479910986.478281] Error processing request: release unlocked lock
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/strands/tsc_y4_ws/src/strands_executive/task_executor/scripts/mdp_task_executor.py", line 161, in add_co_safe_tasks_ros_srv\n    self.service_lock.release()\n', 'error: release unlocked lock\n']
```

**Comment by bfalacerda** [comment]
The task gets added anyway, nothing seems to break
