### ISSUE TITLE
Fix strands_executive compilation so that Jenkins can build it

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_executive#75]
The full long is here: https://gist.github.com/hawesie/227bcd3916260bb056d1#file-strands_executive-jenkins-error-1

The first error I see is :

```
Note: jdd/../../src/jdd/JDDVars.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
error: cannot access jdd.JDD
bad class file: RegularFileObject[../../classes/jdd/JDD.class]
class file has wrong version 52.0, should be 50.0
Please remove or make sure it appears in the correct subdirectory of the classpath.
com.sun.tools.javac.util.Abort
    at com.sun.tools.javac.comp.Check.completionError(Check.java:180)
    at com.sun.tools.javadoc.DocEnv.loadClass(DocEnv.java:159)
    at com.sun.tools.javadoc.RootDocImpl.<init>(RootDocImpl.java:95)
    at com.sun.tools.javadoc.JavadocTool.getRootDocImpl(JavadocTool.java:188)
    at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:364)
    at com.sun.tools.javadoc.Start.begin(Start.java:162)
    at com.sun.tools.javadoc.Main.execute(Main.java:113)
    at com.sun.tools.javah.Main.main(Main.java:153)
javadoc: error - fatal error
```

@BFALacerda I think you've already looked at this, haven't you?

**Comment by bfalacerda** [comment]
Not too much, I still don't know why this happens. What I know now is:
- This was happening when prism was updated, but only once. On the second day it would compile. I don't know why it's happening all the time now, I didn't change anything
- I googled this wrong version error a while ago, and it looks like it's a problem with java compiler versions. The .class files should all be generated by jenkins though, so I don't know why it happens.
